
skillMetadata:
  sections:
    - name: Google AIY Voice Bonnet
      fields:
        - type: label
          label: Enter the colours for the LED. 
    - name: LED colour selection
      fields:
        - name: ledidlecolour
          type: select
          label: LED colour while idle
          options: RED|0;GREEN|1;YELLOW|2;BLUE|3;PURPLE|4;CYAN|5;WHITE|6;OFF|7
          value: 0
        - name: ledlistencolour
          type: text
          label: LED colour while listening for command
          options: RED|0;GREEN|1;YELLOW|2;BLUE|3;PURPLE|4;CYAN|5;WHITE|6;OFF|7
          value: 0
